name: Github CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: macOS-latest
    strategy:
      matrix:
        java_version: [1.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7
      - name: Build project
        run: ./gradlew assemble
      - name: Run tests
        run: ./gradlew test
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.7
        with:
          cmd: ./gradlew cAT
          api: 28
          tag: default
          abi: x86
      - name: Archive Espresso results
        uses: actions/upload-artifact@v1
        with:
          name: Espresso-report
          path: rajawali/build/reports/androidTests/connected
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.7
      - name: Gradle checks
        run: ./gradlew check
      - name: Archive Lint report
        uses: actions/upload-artifact@v1
        with:
          name: Lint-report
          path: rajawali/build/reports/lint-results.html
